//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.225 版自动生成。
// 
#pragma warning disable 1591

namespace SharedWebClassLibrary.hujun64 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Hujun64ServiceSoap", Namespace="http://www.hujun64.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArticleBase))]
    public partial class Hujun64Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PostGuestbookOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteGuestbookOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostArticleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteArticleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Hujun64Service() {
            this.Url = global::SharedWebClassLibrary.Properties.Settings.Default.SharedWebClassLibrary_shfclawyer_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PostGuestbookCompletedEventHandler PostGuestbookCompleted;
        
        /// <remarks/>
        public event DeleteGuestbookCompletedEventHandler DeleteGuestbookCompleted;
        
        /// <remarks/>
        public event PostArticleCompletedEventHandler PostArticleCompleted;
        
        /// <remarks/>
        public event DeleteArticleCompletedEventHandler DeleteArticleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hujun64.com/PostGuestbook", RequestNamespace="http://www.hujun64.com/", ResponseNamespace="http://www.hujun64.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PostGuestbook(string userName, string md5Password, Guestbook guestbook) {
            object[] results = this.Invoke("PostGuestbook", new object[] {
                        userName,
                        md5Password,
                        guestbook});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PostGuestbookAsync(string userName, string md5Password, Guestbook guestbook) {
            this.PostGuestbookAsync(userName, md5Password, guestbook, null);
        }
        
        /// <remarks/>
        public void PostGuestbookAsync(string userName, string md5Password, Guestbook guestbook, object userState) {
            if ((this.PostGuestbookOperationCompleted == null)) {
                this.PostGuestbookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostGuestbookOperationCompleted);
            }
            this.InvokeAsync("PostGuestbook", new object[] {
                        userName,
                        md5Password,
                        guestbook}, this.PostGuestbookOperationCompleted, userState);
        }
        
        private void OnPostGuestbookOperationCompleted(object arg) {
            if ((this.PostGuestbookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostGuestbookCompleted(this, new PostGuestbookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hujun64.com/DeleteGuestbook", RequestNamespace="http://www.hujun64.com/", ResponseNamespace="http://www.hujun64.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteGuestbook(string userName, string md5Password, string guestbookId) {
            object[] results = this.Invoke("DeleteGuestbook", new object[] {
                        userName,
                        md5Password,
                        guestbookId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteGuestbookAsync(string userName, string md5Password, string guestbookId) {
            this.DeleteGuestbookAsync(userName, md5Password, guestbookId, null);
        }
        
        /// <remarks/>
        public void DeleteGuestbookAsync(string userName, string md5Password, string guestbookId, object userState) {
            if ((this.DeleteGuestbookOperationCompleted == null)) {
                this.DeleteGuestbookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteGuestbookOperationCompleted);
            }
            this.InvokeAsync("DeleteGuestbook", new object[] {
                        userName,
                        md5Password,
                        guestbookId}, this.DeleteGuestbookOperationCompleted, userState);
        }
        
        private void OnDeleteGuestbookOperationCompleted(object arg) {
            if ((this.DeleteGuestbookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteGuestbookCompleted(this, new DeleteGuestbookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hujun64.com/PostArticle", RequestNamespace="http://www.hujun64.com/", ResponseNamespace="http://www.hujun64.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PostArticle(string userName, string md5Password, Article article) {
            object[] results = this.Invoke("PostArticle", new object[] {
                        userName,
                        md5Password,
                        article});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PostArticleAsync(string userName, string md5Password, Article article) {
            this.PostArticleAsync(userName, md5Password, article, null);
        }
        
        /// <remarks/>
        public void PostArticleAsync(string userName, string md5Password, Article article, object userState) {
            if ((this.PostArticleOperationCompleted == null)) {
                this.PostArticleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostArticleOperationCompleted);
            }
            this.InvokeAsync("PostArticle", new object[] {
                        userName,
                        md5Password,
                        article}, this.PostArticleOperationCompleted, userState);
        }
        
        private void OnPostArticleOperationCompleted(object arg) {
            if ((this.PostArticleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostArticleCompleted(this, new PostArticleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hujun64.com/DeleteArticle", RequestNamespace="http://www.hujun64.com/", ResponseNamespace="http://www.hujun64.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteArticle(string userName, string md5Password, string articleId) {
            object[] results = this.Invoke("DeleteArticle", new object[] {
                        userName,
                        md5Password,
                        articleId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteArticleAsync(string userName, string md5Password, string articleId) {
            this.DeleteArticleAsync(userName, md5Password, articleId, null);
        }
        
        /// <remarks/>
        public void DeleteArticleAsync(string userName, string md5Password, string articleId, object userState) {
            if ((this.DeleteArticleOperationCompleted == null)) {
                this.DeleteArticleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteArticleOperationCompleted);
            }
            this.InvokeAsync("DeleteArticle", new object[] {
                        userName,
                        md5Password,
                        articleId}, this.DeleteArticleOperationCompleted, userState);
        }
        
        private void OnDeleteArticleOperationCompleted(object arg) {
            if ((this.DeleteArticleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteArticleCompleted(this, new DeleteArticleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hujun64.com/")]
    public partial class Guestbook : ArticleBase {
        
        private string contactField;
        
        private string emailField;
        
        private string replyField;
        
        private string big_class_idField;
        
        private string sexField;
        
        private string ip_fromField;
        
        private string province_fromField;
        
        private System.DateTime replytimeField;
        
        /// <remarks/>
        public string contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string reply {
            get {
                return this.replyField;
            }
            set {
                this.replyField = value;
            }
        }
        
        /// <remarks/>
        public string big_class_id {
            get {
                return this.big_class_idField;
            }
            set {
                this.big_class_idField = value;
            }
        }
        
        /// <remarks/>
        public string sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string ip_from {
            get {
                return this.ip_fromField;
            }
            set {
                this.ip_fromField = value;
            }
        }
        
        /// <remarks/>
        public string province_from {
            get {
                return this.province_fromField;
            }
            set {
                this.province_fromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime replytime {
            get {
                return this.replytimeField;
            }
            set {
                this.replytimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Article))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Guestbook))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hujun64.com/")]
    public partial class ArticleBase {
        
        private string idField;
        
        private string titleField;
        
        private string authorField;
        
        private string contentField;
        
        private string news_fromField;
        
        private string keywordsField;
        
        private bool enabledField;
        
        private bool is_staticField;
        
        private System.DateTime addtimeField;
        
        private System.DateTime last_modField;
        
        private System.DateTime last_visited_timeField;
        
        private int clickField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public string news_from {
            get {
                return this.news_fromField;
            }
            set {
                this.news_fromField = value;
            }
        }
        
        /// <remarks/>
        public string keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
            }
        }
        
        /// <remarks/>
        public bool enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        public bool is_static {
            get {
                return this.is_staticField;
            }
            set {
                this.is_staticField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime addtime {
            get {
                return this.addtimeField;
            }
            set {
                this.addtimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime last_mod {
            get {
                return this.last_modField;
            }
            set {
                this.last_modField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime last_visited_time {
            get {
                return this.last_visited_timeField;
            }
            set {
                this.last_visited_timeField = value;
            }
        }
        
        /// <remarks/>
        public int click {
            get {
                return this.clickField;
            }
            set {
                this.clickField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hujun64.com/")]
    public partial class ArticlePicture {
        
        private string idField;
        
        private string pic_urlField;
        
        private string pic_altField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string pic_url {
            get {
                return this.pic_urlField;
            }
            set {
                this.pic_urlField = value;
            }
        }
        
        /// <remarks/>
        public string pic_alt {
            get {
                return this.pic_altField;
            }
            set {
                this.pic_altField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hujun64.com/")]
    public partial class Article : ArticleBase {
        
        private string class_idField;
        
        private string big_class_idField;
        
        private string module_class_idField;
        
        private bool is_all_classField;
        
        private string ref_idField;
        
        private string ref_by_listField;
        
        private int sort_seqField;
        
        private string[] site_listField;
        
        private ArticlePicture articlePictureField;
        
        /// <remarks/>
        public string class_id {
            get {
                return this.class_idField;
            }
            set {
                this.class_idField = value;
            }
        }
        
        /// <remarks/>
        public string big_class_id {
            get {
                return this.big_class_idField;
            }
            set {
                this.big_class_idField = value;
            }
        }
        
        /// <remarks/>
        public string module_class_id {
            get {
                return this.module_class_idField;
            }
            set {
                this.module_class_idField = value;
            }
        }
        
        /// <remarks/>
        public bool is_all_class {
            get {
                return this.is_all_classField;
            }
            set {
                this.is_all_classField = value;
            }
        }
        
        /// <remarks/>
        public string ref_id {
            get {
                return this.ref_idField;
            }
            set {
                this.ref_idField = value;
            }
        }
        
        /// <remarks/>
        public string ref_by_list {
            get {
                return this.ref_by_listField;
            }
            set {
                this.ref_by_listField = value;
            }
        }
        
        /// <remarks/>
        public int sort_seq {
            get {
                return this.sort_seqField;
            }
            set {
                this.sort_seqField = value;
            }
        }
        
        /// <remarks/>
        public string[] site_list {
            get {
                return this.site_listField;
            }
            set {
                this.site_listField = value;
            }
        }
        
        /// <remarks/>
        public ArticlePicture articlePicture {
            get {
                return this.articlePictureField;
            }
            set {
                this.articlePictureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PostGuestbookCompletedEventHandler(object sender, PostGuestbookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostGuestbookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostGuestbookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteGuestbookCompletedEventHandler(object sender, DeleteGuestbookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteGuestbookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteGuestbookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PostArticleCompletedEventHandler(object sender, PostArticleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostArticleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostArticleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteArticleCompletedEventHandler(object sender, DeleteArticleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteArticleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteArticleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591